### ISSUE TITLE
剧情迷宫挂机无法正常运作

### ISSUE THREAD

**Issue by kirinull** [KarylDAZE/Maa-HBR#11]
### 是否已经存在相同issue?

- [X] 我已经搜索了Issues

### 版本号

0.2.2

### 问题表现

同时点上如(图一)选项后,无法正常剧情迷宫挂机无法正常运作(如图二)
如果只点上启动游戏和剧情迷宫挂机则可以正常运作
具体表现为领取任务奖励无法实现

### 相关 logs

[maa.log](https://github.com/user-attachments/files/17632456/maa.log)

### 截图

![1](https://github.com/user-attachments/assets/dc470a72-8f17-4640-b7f8-5017893d2c37)
![2](https://github.com/user-attachments/assets/956f5ecb-5300-4c00-bc81-e7381e3c0cd8)

**Comment by KarylDAZE** [comment]
已在v0.2.3修复
