### ISSUE TITLE
活动棱镜启动异常问题

### ISSUE THREAD

**Issue by SRThorn** [KarylDAZE/Maa-HBR#12]
### 是否已经存在相同issue?

- [X] 我已经搜索了Issues

### 版本号

Maa-HBR-win-x86_64-v0.2.4

### 问题表现

1.我在任务列表里选了活动棱镜战，但是启动进游戏后一直停在主页不动（脚本任务显示“开始任务：当期活动棱镜战”但是游戏里没动）（见图1）
2.这条是昨天（11.12）发生的——看到停在主页不动的情况，我手动点了下活动，但是立马被脚本退回主页，原样不动。然后我快速地点进活动开启挑战，打完后脚本还是停留在“开始任务：当期活动棱镜战”而不进行下一步。
3.这条是今天（11.13）发生的——依旧是进游戏后停在主页不动，这次我手动点了下活动，脚本终于正常运行了，然后（出于试探的心态）我在它快进入挑战的时候手动点返回，接下来我就停在活动界面什么也没做，但是脚本显示它正常完成了活动棱镜-扭蛋-礼物-任务-时修的流程，然而事实上真正的游戏界面一直没动。（见图2、3）
4.当我觉得可能只是活动棱镜战有bug，故重新尝试换成宝石棱镜的时候，所有流程都能正常运行了。但是这里也有一个问题，就是我是第一次在模拟器上打宝石棱镜，所以进去时要下载资源，而如果我不手动点确认的话脚本也会一直不动。

### 如何复现

任务列表选择当期活动棱镜战，运行程序后发现游戏停在主页不动，而脚本也停留在“开始任务：当期活动棱镜战”，此后若手动点开活动，又会出现问题描述里2、3所提及的问题（我也不知道为什么两次会出现不同的结果，以及我今天再次重新试的时候又出现了2的情况）

### 预期行为

期望应该是正常进入游戏后能按任务列表所指示的一样，进入活动棱镜战（而非卡在主页），然后顺着完成其他流程。

### 相关 logs

我上传了maa.log和maa.bak.log文件，但是它上传之后显示"uploading……"之后就消失了，所以我也不确定有没有上传成功

**Comment by KarylDAZE** [comment]
问题2的原因：活动图标更新后，对主界面的“活动”二字识别出错。
问题3中“脚本显示它正常完成了活动棱镜-扭蛋-礼物-任务-时修的流程”，是因为每个任务识别超时后会自动跳过该任务。

**Comment by KarylDAZE** [comment]
问题2、4已在v0.2.5修复
