### ISSUE TITLE
添加暂停任务功能

### ISSUE THREAD

**Issue by eeeachan27** [KarylDAZE/Maa-HBR#14]
### 是否已经存在相同issue?

- [X] 我已经搜索了Issues

### 版本号

v0.2.10

### 具体内容

例如在进行迷宫挂机的时候需要处理溢出材料，只能停止任务后操作，完成后重新开始任务 会从主页开始重新进行影响效率

**Comment by KarylDAZE** [comment]
1、其实可以在战斗结束返回到地图时快速点开菜单并卖掉材料，然后返回到地图界面即可
2、暂时无法实现暂停任务功能
