### ISSUE TITLE
剧情迷宫挂机异常

### ISSUE THREAD

**Issue by hinaAlter** [KarylDAZE/Maa-HBR#3]
进到第二章day25后会打开队伍页面，开启队伍一览，一直循环向下翻页的操作。当前队伍数量为15。
出现异常后手动停止了任务，并在第二章day25的地图内再次启动任务，什么也没识别到，只是站在原地，24s过后弹出任务完成
![QQ20241027-150011](https://github.com/user-attachments/assets/2d5620b2-d9e4-4ba8-a579-38330de21507)

**Comment by KarylDAZE** [comment]
是不是队伍名称里没有包含队伍序号？

**Comment by hinaAlter** [comment]
> 是不是队伍名称里没有包含队伍序号？
确实是，应该是我队伍命名的问题
