### ISSUE TITLE
关于光球boss的几个问题

### ISSUE THREAD

**Issue by anyoneknowiam** [KarylDAZE/Maa-HBR#7]
大佬你好
不排除自己操作因素的情况下 发现如下几个问题
1.在光球boss节目 似乎无法通过启动游戏回到主页 需要手动 

2.重复刷光球boss功能 似乎无法正常使用 

这两种情况 失败后都会导致在如下图红色方框区域内点击
![1a427fa4d463c09c3bf66b5c6565d684](https://github.com/user-attachments/assets/b45af435-c48f-4b21-978d-f1a703b28b9c)
这是程序截图 停在了光球boss的任务上
![b8b69b8e-92af-49b5-89c7-56fd7bc680ad](https://github.com/user-attachments/assets/863d0c69-187a-4d7a-9d9a-ed4945ea3d5d)

可以知道原因吗？或者有什么解决办法？
希望脚本越做越好

**Comment by KarylDAZE** [comment]
已在v0.2.2修复
