### ISSUE TITLE
请在文档添加请勿使用中文路径的提示

### ISSUE THREAD

**Issue by wess09** [KarylDAZE/Maa-HBR#8]
### 是否已经存在相同issue?

- [X] 我已经搜索了Issues

### 具体内容

有人中招了
![Uploading Image_19643110577323.png…]()

**Comment by wess09** [comment]
中招着QQ810779910

**Comment by KarylDAZE** [comment]
但是我放在中文路径下也可以正常运行？
另外你的截图上传失败了

**Comment by wess09** [comment]
英文就可以正常运行了
