### ISSUE TITLE
如果有多个精选活动能否手动选择第几个

### ISSUE THREAD

**Issue by CCYellowStar2** [KarylDAZE/Maa-HBR#9]
### 是否已经存在相同issue?

- [x] 我已经搜索了Issues

### 具体内容

这期就有两个精选，但默认 打第一个

**Comment by KarylDAZE** [comment]
请更新至v0.2.2

**Comment by CCYellowStar2** [comment]
我已经更新了0.2.2，但精选活动设置是这样的，
![QQ_1730682602615](https://github.com/user-attachments/assets/49119762-0785-40a1-b77e-28ce0a3e098b)
但是我的更新方式是updatexxxx的压缩包，然后我试了完全重新下一个0.2.2就是正常的
![QQ_1730682746676](https://github.com/user-attachments/assets/b87d535e-0595-4219-85dc-a153851a3a1c)

**Comment by KarylDAZE** [comment]
#5  是这样的，因为config/config.json不会自动更新，所以可以手动添加一个新的精选活动棱镜战任务，然后右键删除原本的精选活动棱镜战任务
![image](https://github.com/user-attachments/assets/a5137ce5-43c5-4ced-b193-e881991ddbf4)
